/* Auto-generated by genmsg_cpp for file /home/ubuntu/ros_workspace/rosfred/Planner/msg/Bottle.msg */
#ifndef PLANNER_MESSAGE_BOTTLE_H
#define PLANNER_MESSAGE_BOTTLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Planner
{
template <class ContainerAllocator>
struct Bottle_ {
  typedef Bottle_<ContainerAllocator> Type;

  Bottle_()
  : obj_detected(0)
  , choking(0)
  {
  }

  Bottle_(const ContainerAllocator& _alloc)
  : obj_detected(0)
  , choking(0)
  {
  }

  typedef int32_t _obj_detected_type;
  int32_t obj_detected;

  typedef int32_t _choking_type;
  int32_t choking;


private:
  static const char* __s_getDataType_() { return "Planner/Bottle"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "367d0d65df23e79004c0a4faa4f6193f"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 obj_detected\n\
int32 choking\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, obj_detected);
    ros::serialization::serialize(stream, choking);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, obj_detected);
    ros::serialization::deserialize(stream, choking);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(obj_detected);
    size += ros::serialization::serializationLength(choking);
    return size;
  }

  typedef boost::shared_ptr< ::Planner::Bottle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Planner::Bottle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Bottle
typedef  ::Planner::Bottle_<std::allocator<void> > Bottle;

typedef boost::shared_ptr< ::Planner::Bottle> BottlePtr;
typedef boost::shared_ptr< ::Planner::Bottle const> BottleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Planner::Bottle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Planner::Bottle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Planner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Planner::Bottle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Planner::Bottle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Planner::Bottle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "367d0d65df23e79004c0a4faa4f6193f";
  }

  static const char* value(const  ::Planner::Bottle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x367d0d65df23e790ULL;
  static const uint64_t static_value2 = 0x04c0a4faa4f6193fULL;
};

template<class ContainerAllocator>
struct DataType< ::Planner::Bottle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Planner/Bottle";
  }

  static const char* value(const  ::Planner::Bottle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Planner::Bottle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 obj_detected\n\
int32 choking\n\
\n\
";
  }

  static const char* value(const  ::Planner::Bottle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Planner::Bottle_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Planner::Bottle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.obj_detected);
    stream.next(m.choking);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Bottle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Planner::Bottle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Planner::Bottle_<ContainerAllocator> & v) 
  {
    s << indent << "obj_detected: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obj_detected);
    s << indent << "choking: ";
    Printer<int32_t>::stream(s, indent + "  ", v.choking);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_BOTTLE_H

