/* Auto-generated by genmsg_cpp for file /home/ubuntu/ros_workspace/rosfred/Planner/msg/Mood.msg */
#ifndef PLANNER_MESSAGE_MOOD_H
#define PLANNER_MESSAGE_MOOD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Planner
{
template <class ContainerAllocator>
struct Mood_ {
  typedef Mood_<ContainerAllocator> Type;

  Mood_()
  : data(0)
  , bottle(0)
  {
  }

  Mood_(const ContainerAllocator& _alloc)
  : data(0)
  , bottle(0)
  {
  }

  typedef int32_t _data_type;
  int32_t data;

  typedef int32_t _bottle_type;
  int32_t bottle;


private:
  static const char* __s_getDataType_() { return "Planner/Mood"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "836be3908bb8e2eab0e6fc62f409d4d5"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 data\n\
int32 bottle\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, data);
    ros::serialization::serialize(stream, bottle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, data);
    ros::serialization::deserialize(stream, bottle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(data);
    size += ros::serialization::serializationLength(bottle);
    return size;
  }

  typedef boost::shared_ptr< ::Planner::Mood_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Planner::Mood_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Mood
typedef  ::Planner::Mood_<std::allocator<void> > Mood;

typedef boost::shared_ptr< ::Planner::Mood> MoodPtr;
typedef boost::shared_ptr< ::Planner::Mood const> MoodConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Planner::Mood_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Planner::Mood_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Planner

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Planner::Mood_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Planner::Mood_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Planner::Mood_<ContainerAllocator> > {
  static const char* value() 
  {
    return "836be3908bb8e2eab0e6fc62f409d4d5";
  }

  static const char* value(const  ::Planner::Mood_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x836be3908bb8e2eaULL;
  static const uint64_t static_value2 = 0xb0e6fc62f409d4d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::Planner::Mood_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Planner/Mood";
  }

  static const char* value(const  ::Planner::Mood_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Planner::Mood_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 data\n\
int32 bottle\n\
\n\
";
  }

  static const char* value(const  ::Planner::Mood_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Planner::Mood_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Planner::Mood_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.data);
    stream.next(m.bottle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Mood_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Planner::Mood_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Planner::Mood_<ContainerAllocator> & v) 
  {
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
    s << indent << "bottle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bottle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_MOOD_H

